name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Install requirements
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Build and run
        run: |
          curl -L https://raw.githubusercontent.com/qeeqbox/global-scripts/main/auto-checking.sh -o auto-checking.sh
          chmod +x auto-checking.sh
          ./auto-checking.sh social-analyzer

      - name: Commit changes
        run: |
          git config user.name "qb-auto"
          git config user.email "qbactions@gmail.com"

          git add -- . ':!auto-checking.sh'

          git diff --staged --quiet || git commit -m "🤖"

      - name: Sync and push changes
        run: |
          git pull --rebase origin main
          git push origin HEAD:main

      - name: Delete auto-checking.sh
        if: always()
        run: |
          [ -e auto-checking.sh ] && rm -f auto-checking.sh
